server:
  port: 8081
spring:
  data:
    redis:
      host: 10.10.30.205
      port: 6379
      database: 5
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&charset=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


