server:
  port: 8081
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 5
  datasource:
    url: jdbc:mysql://localhost:8080/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  key: mfo32kt6r
  expire: 3
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      show-values: always