server:
  port: 8080
spring:
  data:
    redis:
      host: 10.10.30.205
      port: 6379
      database: 5
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&charset=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  key: mfo32kt6r
  expire: 3
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      show-values: always


